{{- if .Values.RoleBinding.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.RoleBinding.namespace }}-{{ .Values.RoleBinding.objectId }}-access
  namespace: {{ .Values.RoleBinding.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.RoleBinding.role }}
subjects:
- kind: User
  namespace: {{ .Values.RoleBinding.namespace }}
  name: {{ .Values.RoleBinding.objectId }}
{{- end }}
